<?php

declare(strict_types=1);

// Stored result from Litmus API for a test in sandbox mode, 2022-10-23
// State: complete; all details are populated

return (object)[
    'Html' => null,
    'ID' => 64556223,
    'InboxGUID' => 'gvn1lfg.api',
    'Results' => [
        (object)[
            'ApplicationLongName' => 'Gmail (Edge)',
            'ApplicationName' => 'gmailnew',
            'AverageTimeToProcess' => 34,
            'BusinessOrPopular' => false,
            'Completed' => true,
            'DesktopClient' => false,
            'FoundInSpam' => false,
            'FullpageImage' => 'sandbox.litmus.com/assets/email-sample-fullpage.png',
            'FullpageImageContentBlocking' => 'sandbox.litmus.com/assets/email-sample-fullpage.png',
            'FullpageImageNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-fullpage.png',
            'FullpageImageThumb' => 'sandbox.litmus.com/assets/email-sample-thumb.png',
            'FullpageImageThumbContentBlocking' => 'sandbox.litmus.com/assets/email-sample-thumb.png',
            'FullpageImageThumbNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-thumb.png',
            'Id' => 3409097539,
            'PlatformLongName' => 'Web-based',
            'PlatformName' => 'Web-based',
            'RenderedHtmlUrl' => null,
            'ResultType' => 'email',
            'SpamHeaders' => [],
            'SpamScore' => 0.0,
            'State' => 'complete',
            'Status' => 0,
            'SupportsContentBlocking' => true,
            'WindowImage' => 'sandbox.litmus.com/assets/email-sample-window.png',
            'WindowImageContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window.png',
            'WindowImageNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window.png',
            'WindowImageThumb' => 'sandbox.litmus.com/assets/email-sample-window-thumb.png',
            'WindowImageThumbContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window-thumb.png',
            'WindowImageThumbNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window-thumb.png',
        ],
        (object)[
            'ApplicationLongName' => 'SpamAssassin',
            'ApplicationName' => 'spamassassin3',
            'AverageTimeToProcess' => 368,
            'BusinessOrPopular' => false,
            'Completed' => true,
            'DesktopClient' => false,
            'FoundInSpam' => false,
            'FullpageImage' => 'sandbox.litmus.com/assets/email-sample-fullpage.png',
            'FullpageImageContentBlocking' => 'sandbox.litmus.com/assets/email-sample-fullpage.png',
            'FullpageImageNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-fullpage.png',
            'FullpageImageThumb' => 'sandbox.litmus.com/assets/email-sample-thumb.png',
            'FullpageImageThumbContentBlocking' => 'sandbox.litmus.com/assets/email-sample-thumb.png',
            'FullpageImageThumbNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-thumb.png',
            'Id' => 3409097538,
            'PlatformLongName' => 'Hosted or server-based',
            'PlatformName' => 'Hosted',
            'RenderedHtmlUrl' => null,
            'ResultType' => 'spam',
            'SpamHeaders' => [],
            'SpamScore' => -0.1,
            'State' => 'complete',
            'Status' => 0,
            'SupportsContentBlocking' => false,
            'WindowImage' => 'sandbox.litmus.com/assets/email-sample-window.png',
            'WindowImageContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window.png',
            'WindowImageNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window.png',
            'WindowImageThumb' => 'sandbox.litmus.com/assets/email-sample-window-thumb.png',
            'WindowImageThumbContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window-thumb.png',
            'WindowImageThumbNoContentBlocking' => 'sandbox.litmus.com/assets/email-sample-window-thumb.png',
        ],
    ],
    'Sandbox' => true,
    'Source' => 'https://s3.amazonaws.com/sitevista/6ece85e6-040a-4d67-8971-bf12db9add9f',
    'State' => 'complete',
    'Subject' => 'Reseller SDK sample',
    'TestType' => 'email',
    'UserGuid' => null,
    'ZipFile' => 'http://zip.litmus.com/resellers/?guid=356447df-edfb-4831-812a-eee2e102ce3c',
];
